### ISSUE TITLE
Lambda crashes

### ISSUE THREAD

**Issue by andrew2net** [relaton/api.relaton.org#52]
After updating Relaton on staging, Lambda crashes with the error in the log arn:aws:logs:us-east-1:459474427880:log-group:/aws/lambda/staging-api-relaton-org:*
```
2024-02-06T21:31:53.744-05:00	INIT_START Runtime Version: ruby:2.7.v30	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:274d45caf9cfb7846e5fd3e191c848b67ffddc1c41146accba11437bcd5bc5c4
2024-02-06T21:31:54.127-05:00	/var/lang/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
2024-02-06T21:31:54.127-05:00	To eliminate this warning, please install libyaml and reinstall your ruby.
2024-02-06T21:31:54.127-05:00	Init error when loading handler lib/app.Relaton::Api.handler
2024-02-06T21:31:54.127-05:00	{
                             	  "errorMessage": "libyaml-0.so.2: cannot open shared object file: No such file or directory - /opt/ruby/gems/2.7.0/gems/psych-5.1.2/lib/psych.so",
                             	  "errorType": "Init<LoadError>",
                             	  "stackTrace": [
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/relaton-bib-1.18.2/lib/relaton_bib.rb:2:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/relaton-1.18.0/lib/relaton.rb:1:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:40:in `require'",
                             	    "/var/task/lib/finder.rb:2:in `<top (required)>'",
                             	    "/var/task/lib/app.rb:3:in `require_relative'",
                             	    "/var/task/lib/app.rb:3:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'"
                             	  ]
                             	}
2024-02-06T21:31:54.132-05:00	INIT_REPORT Init Duration: 387.75 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
2024-02-06T21:31:57.489-05:00	/var/lang/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
2024-02-06T21:31:57.489-05:00	To eliminate this warning, please install libyaml and reinstall your ruby.
2024-02-06T21:31:57.489-05:00	Init error when loading handler lib/app.Relaton::Api.handler
2024-02-06T21:31:57.489-05:00	{
                             	  "errorMessage": "libyaml-0.so.2: cannot open shared object file: No such file or directory - /opt/ruby/gems/2.7.0/gems/psych-5.1.2/lib/psych.so",
                             	  "errorType": "Init<LoadError>",
                             	  "stackTrace": [
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/relaton-bib-1.18.2/lib/relaton_bib.rb:2:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/relaton-1.18.0/lib/relaton.rb:1:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:40:in `require'",
                             	    "/var/task/lib/finder.rb:2:in `<top (required)>'",
                             	    "/var/task/lib/app.rb:3:in `require_relative'",
                             	    "/var/task/lib/app.rb:3:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'"
                             	  ]
                             	}
2024-02-06T21:31:57.626-05:00	INIT_REPORT Init Duration: 3411.09 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
2024-02-06T21:31:57.626-05:00	START RequestId: 847ee114-0b5a-4c5c-8cd4-807b1d16eb38 Version: $LATEST
2024-02-06T21:31:57.627-05:00	Unknown application error occurred
                             	Runtime.Unknown
2024-02-06T21:31:57.627-05:00	END RequestId: 847ee114-0b5a-4c5c-8cd4-807b1d16eb38
2024-02-06T21:31:57.627-05:00	REPORT RequestId: 847ee114-0b5a-4c5c-8cd4-807b1d16eb38	Duration: 3431.44 ms	Billed Duration: 3432 ms	Memory Size: 128 MB	Max Memory Used: 16 MB	
2024-02-06T21:31:57.744-05:00	INIT_START Runtime Version: ruby:2.7.v30	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:274d45caf9cfb7846e5fd3e191c848b67ffddc1c41146accba11437bcd5bc5c4
2024-02-06T21:31:57.998-05:00	/var/lang/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
2024-02-06T21:31:57.998-05:00	To eliminate this warning, please install libyaml and reinstall your ruby.
2024-02-06T21:31:57.998-05:00	Init error when loading handler lib/app.Relaton::Api.handler
2024-02-06T21:31:57.998-05:00	{
                             	  "errorMessage": "libyaml-0.so.2: cannot open shared object file: No such file or directory - /opt/ruby/gems/2.7.0/gems/psych-5.1.2/lib/psych.so",
                             	  "errorType": "Init<LoadError>",
                             	  "stackTrace": [
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:149:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/relaton-bib-1.18.2/lib/relaton_bib.rb:2:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'",
                             	    "/opt/ruby/gems/2.7.0/gems/relaton-1.18.0/lib/relaton.rb:1:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:40:in `require'",
                             	    "/var/task/lib/finder.rb:2:in `<top (required)>'",
                             	    "/var/task/lib/app.rb:3:in `require_relative'",
                             	    "/var/task/lib/app.rb:3:in `<top (required)>'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'",
                             	    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'"
                             	  ]
                             	}
2024-02-06T21:31:58.002-05:00	INIT_REPORT Init Duration: 258.53 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
```

**Comment by phuonghuynh** [comment]
We using ruby3.2 for new version, but the layer for it support max ruby2.7 as link https://github.com/lambci/docker-lambda
So I replacing the builder for lambda layer to support ruby3.2.
I will also update docker/infra stuff to read versioning from configurable file in root folder, i.e. `.ruby-version`...
